/**
 * Global Presence map markers and site addresses.
 * x / y are percentages of the map image (origin top-left).
 * Positions traced from the Global Presence map artwork.
 *
 * Addresses are the certified units and offices. The same site listed under
 * more than one certificate is stored once.
 */

export const PRESENCE_TYPES = {
  client: { label: 'Our Clients', color: '#84000C' },
  office: { label: 'Office / Warehouse', color: '#3B6FD8' },
  hub: { label: 'Office / Warehouse & Clients', color: '#C42A7A' },
};

export const PRESENCE_LOCATIONS = [
  /* Hubs — 3 */
  {
    id: 'mexico',
    countryId: 'mexico',
    name: 'Mexico',
    country: 'Mexico',
    type: 'hub',
    x: 17.3,
    y: 53.7,
    primary: true,
  },
  {
    id: 'south-africa',
    countryId: 'south-africa',
    name: 'South Africa',
    country: 'South Africa',
    type: 'hub',
    x: 54.5,
    y: 83.5,
    primary: true,
  },
  {
    id: 'southeast-asia',
    countryId: 'southeast-asia',
    name: 'Southeast Asia',
    country: 'Southeast Asia',
    type: 'hub',
    x: 81.0,
    y: 68.4,
    primary: true,
  },

  /* Offices / warehouses */
  {
    id: 'usa-east',
    countryId: 'usa',
    name: 'United States',
    country: 'United States',
    type: 'office',
    x: 19.4,
    y: 49.9,
    primary: true,
  },
  {
    id: 'united-kingdom',
    countryId: 'united-kingdom',
    name: 'United Kingdom',
    country: 'United Kingdom',
    type: 'office',
    x: 44.3,
    y: 32.6,
    primary: true,
  },
  {
    id: 'germany',
    countryId: 'germany',
    name: 'Germany',
    country: 'Germany',
    type: 'office',
    x: 50.0,
    y: 38.9,
    primary: true,
  },
  {
    id: 'austria',
    countryId: 'austria',
    name: 'Austria',
    country: 'Austria',
    type: 'office',
    x: 52.4,
    y: 40.6,
    primary: true,
  },
  {
    id: 'spain',
    countryId: 'spain',
    name: 'Spain',
    country: 'Spain',
    type: 'office',
    x: 44.2,
    y: 44.4,
    primary: true,
  },
  {
    id: 'portugal',
    countryId: 'portugal',
    name: 'Portugal',
    country: 'Portugal',
    type: 'office',
    x: 42.0,
    y: 43.0,
    primary: true,
  },
  {
    id: 'uae',
    countryId: 'uae',
    name: 'United Arab Emirates',
    country: 'United Arab Emirates',
    type: 'office',
    x: 60.8,
    y: 54.3,
    primary: true,
  },
  {
    id: 'india',
    countryId: 'india',
    name: 'India',
    country: 'India',
    type: 'office',
    x: 69.1,
    y: 55.2,
    primary: true,
  },
  {
    id: 'china',
    countryId: 'china',
    name: 'China',
    country: 'China',
    type: 'office',
    x: 71.7,
    y: 46.2,
    primary: true,
  },
  {
    id: 'brazil',
    countryId: 'brazil',
    name: 'Brazil',
    country: 'Brazil',
    type: 'office',
    x: 26.4,
    y: 58.7,
    primary: true,
  },

  /* Client locations */
  {
    id: 'canada',
    countryId: 'canada',
    name: 'Canada',
    country: 'Canada',
    type: 'client',
    x: 22.4,
    y: 38.9,
    primary: true,
  },
  {
    id: 'usa-west',
    countryId: 'usa',
    name: 'United States — West',
    country: 'United States',
    type: 'client',
    x: 14.5,
    y: 43.5,
  },
  {
    id: 'usa-midwest',
    countryId: 'usa',
    name: 'United States — Midwest',
    country: 'United States',
    type: 'client',
    x: 19.9,
    y: 43.6,
  },
  {
    id: 'argentina',
    countryId: 'argentina',
    name: 'Argentina',
    country: 'Argentina',
    type: 'client',
    x: 21.3,
    y: 48.2,
    primary: true,
  },
  {
    id: 'chile',
    countryId: 'chile',
    name: 'Chile',
    country: 'Chile',
    type: 'client',
    x: 18.8,
    y: 51.9,
    primary: true,
  },
  {
    id: 'france',
    countryId: 'france',
    name: 'France',
    country: 'France',
    type: 'client',
    x: 46.3,
    y: 33.6,
    primary: true,
  },
  {
    id: 'italy',
    countryId: 'italy',
    name: 'Italy',
    country: 'Italy',
    type: 'client',
    x: 49.5,
    y: 33.9,
    primary: true,
  },
  {
    id: 'poland',
    countryId: 'poland',
    name: 'Poland',
    country: 'Poland',
    type: 'client',
    x: 52.6,
    y: 32.0,
    primary: true,
  },
  {
    id: 'turkey',
    countryId: 'turkey',
    name: 'Turkey',
    country: 'Turkey',
    type: 'client',
    x: 57.1,
    y: 38.5,
    primary: true,
  },
  {
    id: 'egypt',
    countryId: 'egypt',
    name: 'Egypt',
    country: 'Egypt',
    type: 'client',
    x: 56.8,
    y: 49.9,
    primary: true,
  },
  {
    id: 'morocco',
    countryId: 'morocco',
    name: 'Morocco',
    country: 'Morocco',
    type: 'client',
    x: 46.2,
    y: 46.2,
    primary: true,
  },
  {
    id: 'nigeria',
    countryId: 'nigeria',
    name: 'Nigeria',
    country: 'Nigeria',
    type: 'client',
    x: 54.5,
    y: 76.3,
    primary: true,
  },
  {
    id: 'kenya',
    countryId: 'kenya',
    name: 'Kenya',
    country: 'Kenya',
    type: 'client',
    x: 55.7,
    y: 67.7,
    primary: true,
  },
  {
    id: 'saudi-arabia',
    countryId: 'saudi-arabia',
    name: 'Saudi Arabia',
    country: 'Saudi Arabia',
    type: 'client',
    x: 61.0,
    y: 47.2,
    primary: true,
  },
  {
    id: 'bangladesh',
    countryId: 'bangladesh',
    name: 'Bangladesh',
    country: 'Bangladesh',
    type: 'client',
    x: 72.2,
    y: 50.3,
    primary: true,
  },
  {
    id: 'japan',
    countryId: 'japan',
    name: 'Japan',
    country: 'Japan',
    type: 'client',
    x: 78.2,
    y: 46.2,
    primary: true,
  },
  {
    id: 'south-korea',
    countryId: 'south-korea',
    name: 'South Korea',
    country: 'South Korea',
    type: 'client',
    x: 74.0,
    y: 52.8,
    primary: true,
  },
  {
    id: 'australia',
    countryId: 'australia',
    name: 'Australia',
    country: 'Australia',
    type: 'client',
    x: 87.0,
    y: 80.6,
    primary: true,
  },
  {
    id: 'new-zealand',
    countryId: 'new-zealand',
    name: 'New Zealand',
    country: 'New Zealand',
    type: 'client',
    x: 94.5,
    y: 88.2,
    primary: true,
  },
  {
    id: 'russia',
    countryId: 'russia',
    name: 'Russia',
    country: 'Russia',
    type: 'client',
    x: 74.0,
    y: 27.0,
    primary: true,
  },
];

export const PRESENCE_ADDRESSES = {
  india: [
    {
      label: 'Factory & Registered Office',
      title: 'Unit 1 — Jaitpura',
      lines: [
        'Mayur Uniquoters Limited',
        'Village Jaitpura, Jaipur–Sikar Road',
        'Jaipur 303704, Rajasthan, India',
      ],
      phones: ['+91-1423-224001'],
      faxes: ['+91-1423-224420'],
      emails: ['info@mayur.biz'],
    },
    {
      label: 'Correspondence',
      title: 'Jaipur Office',
      lines: [
        'Mayur Uniquoters Limited',
        '28, 4th Floor, Lakshmi Complex',
        'M.I. Road, Jaipur 302001',
        'Rajasthan, India',
      ],
      phones: ['+91-141-2361132'],
      faxes: ['+91-141-2365423'],
      emails: ['info@mayur.biz'],
    },
    {
      label: 'Manufacturing',
      title: 'Unit 2 — Dhodsar',
      lines: [
        'Mayur Uniquoters Limited',
        'Village Dhodsar, Khasra No. 690/2, 691/2 & 693',
        'Khajroli Link Road, Near Ratan Devi College',
        'Jaipur–Sikar Highway, Jaipur 303712',
        'Rajasthan, India',
      ],
    },
    {
      label: 'Manufacturing',
      title: 'Unit 3 — Banmore',
      lines: [
        'Mayur Uniquoters Limited',
        'Plot No. S-1 to S-30 and M-8 to M-13',
        'Sitapur Industrial Area, Phase-1',
        'Village Dhanela, Banmore, Morena 476444',
        'Madhya Pradesh, India',
      ],
    },
    {
      label: 'Office',
      title: 'Bangalore',
      lines: [
        'Mayur Uniquoters Limited',
        '204, Second Floor, I-N Block',
        'Opp. Vidya Vardhak Sangha, Rajaji Nagar',
        'Bangalore 560010, India',
      ],
      phones: ['+91-80-32955073', '+91-80-41711881'],
    },
    {
      label: 'Office',
      title: 'Delhi',
      lines: [
        'Mayur Uniquoters Limited',
        '4382, B-Block, Pocket No. 5 & 6',
        'Vasant Kunj, New Delhi 110070',
        'India',
      ],
      phones: ['+91-11-45082516'],
    },
  ],
  usa: [
    {
      label: 'Office',
      title: 'Dallas',
      lines: [
        'Mayur Uniquoters Corp.',
        '1999, Bryan Street, Suite 900',
        'Dallas, TX 75201-3140',
        'USA',
      ],
    },
    {
      label: 'Office',
      title: 'Futura Textiles',
      lines: ['Futura Textiles', '8709 Caroma Street', 'Olive Branch, MS 38654', 'USA'],
      phones: ['+1-877-426-8177'],
      emails: ['office@futuratextiles.com'],
      websites: [{ href: 'https://www.futuratextiles.com', label: 'futuratextiles.com' }],
    },
  ],
  mexico: [
    {
      label: 'Logistics, Sales, Warehousing',
      title: 'Arteaga',
      lines: [
        'Mayur Uniquoters Corp.',
        'C/o Vitti Logistics S de RL de CV',
        'Boulevard Campestre 302, Parque Industrial Server',
        'Arteaga, Coahuila, CP 25354',
        'Mexico',
      ],
    },
    {
      label: 'Logistics, Sales, Warehousing',
      title: 'Saltillo',
      lines: [
        'Mayur Uniquoters Corp.',
        'Vitti Logistics S de RL de CV / ZAI Logistics',
        'Carretera Saltillo–Monterrey KM 5.5, No. 7290',
        'Los Rodríguez, Saltillo, Coahuila',
        'México, CP 25200',
      ],
    },
  ],
  'south-africa': [
    {
      label: 'Logistics, Sales, Warehousing',
      title: 'Durban',
      lines: [
        'Mayur Uniquoters SA (Pty) Ltd.',
        'C/O Feltex Foam, 291 Paisley Road',
        'Jacobs, Durban, KwaZulu-Natal 4026',
        'South Africa',
      ],
    },
    {
      label: 'Office',
      title: 'Johannesburg',
      lines: ['P.O. Box 52310', 'Saxonwold, Johannesburg', 'Gauteng 2132', 'South Africa'],
    },
  ],
  austria: [
    {
      label: 'International Office',
      title: 'Salzburg',
      lines: ['Otto-von-Lilienthalstrasse 102', '5020 Salzburg', 'Austria'],
    },
  ],
  portugal: [
    {
      label: 'International Office',
      title: 'Porto',
      lines: ['Rua Capitão Henrique Galvão, 146-4Esq.', '4050-300 Porto', 'Portugal'],
    },
  ],
};
